package com.kapitek.aggregator.kapitek_transaction_aggregate_service.domain.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

import java.util.Arrays;

@Getter
@RequiredArgsConstructor
public enum MerchantCategoryCodes {

    HOLIDAY_INNS("3501", "Holiday Inns", "V,M", MerchantCategory.ACCOMMODATION),
    BEST_WESTERN("3502", "Best Western", "V,M", MerchantCategory.ACCOMMODATION),
    SHERATON("3503", "Sheraton", "V,M", MerchantCategory.ACCOMMODATION),
    HILTON("3504", "Hilton", "V,M", MerchantCategory.ACCOMMODATION),
    TRUSTHOUSE_FORTE("3505", "Trusthouse Forte", "V,M", MerchantCategory.ACCOMMODATION),
    GOLDEN_TULIP("3506", "Golden Tulip", "V,M", MerchantCategory.ACCOMMODATION),
    FRIENDSHIP_INNS_INTERNATIONAL("3507", "Friendship Inns International", "V,M", MerchantCategory.ACCOMMODATION),
    QUALITY_INTERNATIONAL("3508", "Quality International", "V,M", MerchantCategory.ACCOMMODATION),
    MARRIOTT("3509", "Marriott", "V,M", MerchantCategory.ACCOMMODATION),
    DAYS_INNS_OF_AMERICA("3510", "Days Inns Of America", "V,M", MerchantCategory.ACCOMMODATION),
    ARABELLA_HOTELS("3511", "Arabella Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    INTERCONTINENTAL("3512", "Intercontinental", "V,M", MerchantCategory.ACCOMMODATION),
    WESTIN_HOTELS("3513", "Westin Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    AMERISUITES("3514", "Amerisuites", "V,M", MerchantCategory.ACCOMMODATION),
    RODEWAY_INNS_INTERNATIONAL("3515", "Rodeway Inns International", "V,M", MerchantCategory.ACCOMMODATION),
    LA_QUINTA_MOTOR_INNS("3516", "La Quinta Motor Inns", "V,M", MerchantCategory.ACCOMMODATION),
    AMERICANA_HOTELS_CORPORATION("3517", "Americana Hotels Corporation", "V,M", MerchantCategory.ACCOMMODATION),
    SOL_HOTELS("3518", "Sol Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    PLM_ETAP_INTERNATIONAL("3519", "PLM/ETAP International", "V,M", MerchantCategory.ACCOMMODATION),
    MERIDIEN("3520", "Meridien", "V,M", MerchantCategory.ACCOMMODATION),
    CREST_HOTELS("3521", "Crest Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    TOKYO_GROUP("3522", "Tokyo Group", "V,M", MerchantCategory.ACCOMMODATION),
    PENINSULA_HOTELS("3523", "Peninsula Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    WELCOMGROUP("3524", "Welcomgroup", "V,M", MerchantCategory.ACCOMMODATION),
    DUNFEY_HOTELS("3525", "Dunfey Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    PRINCE_HOTELS("3526", "Prince Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    DOWNTOWNER_PASSPORT("3527", "Downtowner Passport", "V,M", MerchantCategory.ACCOMMODATION),
    THUNDERBIRD_RED_LION("3528", "Thunderbird/Red Lion", "V,M", MerchantCategory.ACCOMMODATION),
    CP_CANADIAN_PACIFIC("3529", "CP (Canadian Pacific)", "V,M", MerchantCategory.ACCOMMODATION),
    RENAISSANCE_HOTELS("3530", "Renaissance Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    KAUAI_COCONUT_BEACH_RESORT("3531", "Kauai Coconut Beach Resort", "V,M", MerchantCategory.ACCOMMODATION),
    ROYAL_KONA_RESORT("3532", "Royal Kona Resort", "V,M", MerchantCategory.ACCOMMODATION),
    PARK_INN_BY_RADISSON("3533", "Park Inn by Radisson", "V,M", MerchantCategory.ACCOMMODATION),
    SOUTHERN_PACIFIC_HOTEL("3534", "Southern Pacific Hotel", "V,M", MerchantCategory.ACCOMMODATION),
    HILTON_INTERNATIONAL("3535", "Hilton International", "V,M", MerchantCategory.ACCOMMODATION),
    AMFAC_HOTELS("3536", "AMFAC Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    ANA_HOTELS("3537", "Ana Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    CONCORDE_HOTELS("3538", "Concorde Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    SUMMERFIELD_SUITES_HOTEL("3539", "Summerfield Suites Hotel", "V,M", MerchantCategory.ACCOMMODATION),
    IBEROTEL("3540", "Iberotel", "V,M", MerchantCategory.ACCOMMODATION),
    HOTEL_OKURA("3541", "Hotel Okura", "V,M", MerchantCategory.ACCOMMODATION),
    ROYAL_HOTELS("3542", "Royal Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    FOUR_SEASONS("3543", "Four Seasons", "V,M", MerchantCategory.ACCOMMODATION),
    CIGAHOTELS("3544", "Cigahotels", "V,M", MerchantCategory.ACCOMMODATION),
    SHANGRI_LA_INTERNATIONAL("3545", "Shangri-La International", "V,M", MerchantCategory.ACCOMMODATION),
    HOTEL_SIERRA("3546", "Hotel Sierra", "V,M", MerchantCategory.ACCOMMODATION),
    BREAKERS_RESORT("3547", "Breakers Resort", "M", MerchantCategory.ACCOMMODATION),
    HOTELS_MELIA("3548", "Hotels Melia", "V,M", MerchantCategory.ACCOMMODATION),
    AUBERGE_DES_GOVERNEURS("3549", "Auberge Des Governeurs", "V,M", MerchantCategory.ACCOMMODATION),
    REGAL_8_INNS("3550", "Regal 8 Inns", "V,M", MerchantCategory.ACCOMMODATION),
    MIRAGE_HOTEL_AND_CASINO("3551", "Mirage Hotel and Casino", "V,M", MerchantCategory.ACCOMMODATION),
    COAST_HOTELS("3552", "Coast Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    PARKS_INNS_INTERNATIONAL("3553", "Parks Inns International", "V,M", MerchantCategory.ACCOMMODATION),
    PINEHURST_RESORT("3554", "Pinehurst Resort", "V,M", MerchantCategory.ACCOMMODATION),
    TREASURE_ISLAND_HOTEL_AND_CASINO("3555", "Treasure Island Hotel and Casino", "V,M", MerchantCategory.ACCOMMODATION),
    BARTON_CREEK_RESORT("3556", "Barton Creek Resort", "V,M", MerchantCategory.ACCOMMODATION),
    MANHATTAN_EAST_SUITE_HOTELS("3557", "Manhattan East Suite Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    JOLLY_HOTELS("3558", "Jolly Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    CANDLEWOOD_SUITES("3559", "Candlewood Suites", "V,M", MerchantCategory.ACCOMMODATION),
    ALADDIN_RESORT_AND_CASINO("3560", "Aladdin Resort and Casino", "V,M", MerchantCategory.ACCOMMODATION),
    GOLDEN_NUGGET("3561", "Golden Nugget", "V,M", MerchantCategory.ACCOMMODATION),
    COMFORT_HOTEL_INTERNATIONAL("3562", "Comfort Hotel International", "V,M", MerchantCategory.ACCOMMODATION),
    JOURNEYS_END_MOTELS("3563", "Journeys End Motels", "V,M", MerchantCategory.ACCOMMODATION),
    SAMS_TOWN_HOTEL_AND_CASINO("3564", "Sams Town Hotel and Casino", "V,M", MerchantCategory.ACCOMMODATION),
    RELAX_INNS("3565", "Relax Inns", "V,M", MerchantCategory.ACCOMMODATION),
    GARDEN_PLACE_HOTEL("3566", "Garden Place Hotel", "V,M", MerchantCategory.ACCOMMODATION),
    SOHO_GRAND_HOTEL("3567", "Soho Grand Hotel", "V,M", MerchantCategory.ACCOMMODATION),
    LADBROKE_HOTELS("3568", "Ladbroke Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    TRIBECA_GRAND_HOTEL("3569", "Tribeca Grand Hotel", "V,M", MerchantCategory.ACCOMMODATION),
    GRAND_MET_FORUM_HOTELS("3570", "Grand Met Forum Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    GRAND_WAILEA_RESORT("3571", "Grand Wailea Resort", "V,M", MerchantCategory.ACCOMMODATION),
    MIYAKO_HOTEL_KINTETSU("3572", "Miyako Hotel/Kintetsu", "V,M", MerchantCategory.ACCOMMODATION),
    SANDMAN_HOTELS("3573", "Sandman Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    VENTURE_INN("3574", "Venture Inn", "V,M", MerchantCategory.ACCOMMODATION),
    VAGABOND_HOTELS("3575", "Vagabond Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    LA_QUINTA_RESORT("3576", "La Quinta Resort", "V,M", MerchantCategory.ACCOMMODATION),
    MANDARIN_INTERNATIONAL("3577", "Mandarin International", "V,M", MerchantCategory.ACCOMMODATION),
    FRANKENMUTH_BAVARIAN("3578", "Frankenmuth Bavarian", "V,M", MerchantCategory.ACCOMMODATION),
    HOTEL_MERCURE("3579", "Hotel Mercure", "V,M", MerchantCategory.ACCOMMODATION),
    HOTEL_DEL_CORONADO("3580", "Hotel Del Coronado", "V,M", MerchantCategory.ACCOMMODATION),
    DELTA_HOTELS("3581", "Delta Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    CALIFORNIA_HOTEL_AND_CASINO("3582", "California Hotel and Casino", "V,M", MerchantCategory.ACCOMMODATION),
    RADISSON_BLU("3583", "Radisson BLU", "V,M", MerchantCategory.ACCOMMODATION),
    PRINCESS_HOTELS_INTERNATIONAL("3584", "Princess Hotels International", "V,M", MerchantCategory.ACCOMMODATION),
    HUNGAR_HOTELS("3585", "Hungar Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    SOKOS_HOTELS("3586", "Sokos Hotel", "V,M", MerchantCategory.ACCOMMODATION),
    DORAL_HOTELS("3587", "Doral Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    HELMSLEY_HOTELS("3588", "Helmsley Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    DORAL_GOLF_RESORT("3589", "Doral Golf Resort", "V,M", MerchantCategory.ACCOMMODATION),
    FAIRMONT_HOTELS_CORPORATION("3590", "Fairmont Hotels Corporation", "V,M", MerchantCategory.ACCOMMODATION),
    SONESTA_INTERNATIONAL_HOTELS("3591", "Sonesta International Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    OMNI_INTERNATIONAL("3592", "Omni International", "V,M", MerchantCategory.ACCOMMODATION),
    CUNARD_HOTELS("3593", "Cunard Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    ARIZONA_BILTMORE("3594", "Arizona Biltmore", "V,M", MerchantCategory.ACCOMMODATION),
    HOSPITALITY_INNS("3595", "Hospitality Inns", "V,M", MerchantCategory.ACCOMMODATION),
    WYNN_LAS_VEGAS("3596", "Wynn Las Vegas", "V,M", MerchantCategory.ACCOMMODATION),
    RIVERSIDE_RESORT_AND_CASINO("3597", "Riverside Resort and Casino", "V,M", MerchantCategory.ACCOMMODATION),
    REGENT_HOTELS("3598", "Regent Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    PANNONIA_HOTELS("3599", "Pannonia Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    SADDLEBROOK_RESORT_TAMPA("3600", "Saddlebrook Resort–Tampa", "V,M", MerchantCategory.ACCOMMODATION),
    TRADEWINDS_RESORT("3601", "Tradewinds Resort", "V,M", MerchantCategory.ACCOMMODATION),
    HUDSON_HOTEL("3602", "Hudson Hotel", "V,M", MerchantCategory.ACCOMMODATION),
    NOAHS_HOTEL_MELBOURNE("3603", "Noahs Hotel (Melbourne)", "V,M", MerchantCategory.ACCOMMODATION),
    HILTON_GARDEN_INN("3604", "Hilton Garden Inn", "V,M", MerchantCategory.ACCOMMODATION),
    JURYS_DOYLE_HOTEL_GROUP("3605", "Jurys Doyle Hotel Group", "M", MerchantCategory.ACCOMMODATION),
    JEFFERSON_HOTEL("3606", "Jefferson Hotel", "M", MerchantCategory.ACCOMMODATION),
    FONTAINEBLEAU_RESORT("3607", "Fontainebleau Resort", "V,M", MerchantCategory.ACCOMMODATION),
    GAYLORD_OPRYLAND("3608", "Gaylord Opryland", "V,M", MerchantCategory.ACCOMMODATION),
    GAYLORD_PALMS("3609", "Gaylord Palms", "V,M", MerchantCategory.ACCOMMODATION),
    GAYLORD_TEXAN("3610", "Gaylord Texan", "M", MerchantCategory.ACCOMMODATION),
    C_MON_INN("3611", "C MON INN", "M", MerchantCategory.ACCOMMODATION),
    MOEVENPICK("3612", "Moevenpick", "V,M", MerchantCategory.ACCOMMODATION),
    MICROTEL_INN_AND_SUITES("3613", "Microtel Inn and Suites", "V,M", MerchantCategory.ACCOMMODATION),
    AMERICINN("3614", "AmericInn", "V,M", MerchantCategory.ACCOMMODATION),
    TRAVELODGE_MOTELS("3615", "Travelodge Motels", "V,M", MerchantCategory.ACCOMMODATION),
    HERMITAGE_HOTELS("3616", "Hermitage Hotels", "M", MerchantCategory.ACCOMMODATION),
    AMERICAS_BEST_VALUE_INN("3617", "America’s Best Value Inn", "V,M", MerchantCategory.ACCOMMODATION),
    GREAT_WOLF("3618", "Great Wolf", "V,M", MerchantCategory.ACCOMMODATION),
    ALOFT("3619", "Aloft", "V,M", MerchantCategory.ACCOMMODATION),
    BINIONS_HORSESHOE_CLUB("3620", "Binions Horseshoe Club", "V,M", MerchantCategory.ACCOMMODATION),
    EXTENDED_STAY("3621", "Extended Stay", "V,M", MerchantCategory.ACCOMMODATION),
    MERLIN_HOTEL_PERTH("3622", "Merlin Hotel (Perth)", "V,M", MerchantCategory.ACCOMMODATION),
    DORINT_HOTELS("3623", "Dorint Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    LADY_LUCK_HOTEL_AND_CASINO("3624", "Lady Luck Hotel and Casino", "V,M", MerchantCategory.ACCOMMODATION),
    HOTEL_UNIVERSAL("3625", "Hotel Universal", "V,M", MerchantCategory.ACCOMMODATION),
    STUDIO_PLUS("3626", "Studio Plus", "V,M", MerchantCategory.ACCOMMODATION),
    EXTENDED_STAY_AMERICA("3627", "Extended Stay America", "V,M", MerchantCategory.ACCOMMODATION),
    EXCALIBUR_HOTEL_CASINO("3628", "Excalibur Hotel and Casino", "V,M", MerchantCategory.ACCOMMODATION),
    DAN_HOTELS("3629", "Dan Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    EXTENDED_STAY_DELUXE("3630", "Extended Stay Deluxe", "V,M", MerchantCategory.ACCOMMODATION),
    SLEEP_INN("3631", "Sleep Inn", "V,M", MerchantCategory.ACCOMMODATION),
    THE_PHOENICIAN("3632", "The Phoenician", "V,M", MerchantCategory.ACCOMMODATION),
    RANK_HOTELS("3633", "Rank Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    SWISSOTEL("3634", "Swissotel", "V,M", MerchantCategory.ACCOMMODATION),
    RESO_HOTELS("3635", "Reso Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    SAROVA_HOTELS("3636", "Sarova Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    RAMADA_INNS("3637", "Ramada Inns", "V,M", MerchantCategory.ACCOMMODATION),
    HOWARD_JOHNSON("3638", "Howard Johnson", "V,M", MerchantCategory.ACCOMMODATION),
    MOUNT_CHARLOTTE_HOTELS("3639", "Mount Charlotte Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    HYATT_HOTELS_INTERNATIONAL("3640", "Hyatt Hotels/International", "V,M", MerchantCategory.ACCOMMODATION),
    SOFITEL_HOTELS("3641", "Sofitel Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    NOVOTEL_SIEH_ACC0R("3642", "Novotel Sieh (Accor)", "V,M", MerchantCategory.ACCOMMODATION),
    STEIGENBERGER("3643", "Steigenberger", "V,M", MerchantCategory.ACCOMMODATION),
    ECONO_TRAVEL_MOTOR_HOTEL("3644", "Econo-Travel Motor Hotel", "V,M", MerchantCategory.ACCOMMODATION),
    QUEENS_MOAT_HOUSES("3645", "Queens Moat Houses", "V,M", MerchantCategory.ACCOMMODATION),
    SWALLOW_HOTELS("3646", "Swallow Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    GRUPO_HOTELS_HUSA_SA("3647", "Grupo Hotels HUSA SA", "V,M", MerchantCategory.ACCOMMODATION),
    DE_VERE_HOTELS("3648", "De Vere Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    RADISSON("3649", "Radisson", "V,M", MerchantCategory.ACCOMMODATION),
    RED_ROOF_INNS("3650", "Red Roof Inns", "V,M", MerchantCategory.ACCOMMODATION),
    IMPERIAL_LONDON_HOTELS("3651", "Imperial London Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    EMBASSY_HOTELS("3652", "Embassy Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    PENTA_HOTELS("3653", "Penta Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    LOEWS_HOTELS("3654", "Loews Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    SCANDIC_HOTELS("3655", "Scandic Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    SARA_HOTELS("3656", "Sara Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    OBEROI_HOTELS("3657", "Oberoi Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    NEW_OTANI_HOTELS("3658", "New Otani Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    TAJ_HOTELS_INTL("3659", "Taj Hotels Intl", "V,M", MerchantCategory.ACCOMMODATION),
    KNIGHTS_INN("3660", "Knights Inn", "V,M", MerchantCategory.ACCOMMODATION),
    METROPOLE_HOTELS("3661", "Metropole Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    CIRCUS_CIRCUS_HOTEL_CASINO("3662", "Circus Circus Hotel and Casino", "V,M", MerchantCategory.ACCOMMODATION),
    HOTELES_EL_PRESIDENTE("3663", "Hoteles El Presidente", "V,M", MerchantCategory.ACCOMMODATION),
    FLAG_INNS("3664", "Flag Inns", "V,M", MerchantCategory.ACCOMMODATION),
    HAMPTON_INNS("3665", "Hampton Inns", "V,M", MerchantCategory.ACCOMMODATION),
    STAKIS_HOTELS("3666", "Stakis Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    LUXOR_HOTEL_CASINO("3667", "Luxor Hotel and Casino", "V,M", MerchantCategory.ACCOMMODATION),
    MARITIM("3668", "Maritim", "V,M", MerchantCategory.ACCOMMODATION),
    ELDORADO_HOTEL_CASINO("3669", "Eldorado Hotel and Casino", "V,M", MerchantCategory.ACCOMMODATION),
    ARCADE("3670", "Arcade", "V,M", MerchantCategory.ACCOMMODATION),
    ARCTIA("3671", "Arctia", "V,M", MerchantCategory.ACCOMMODATION),
    CAMPANILE("3672", "Campanile", "V,M", MerchantCategory.ACCOMMODATION),
    IBUSZ_HOTELS("3673", "Ibusz Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    RANTASIPI_HOTELS("3674", "Rantasipi Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    INTERHOTEL_CEDOK("3675", "Interhotel Cedok", "V,M", MerchantCategory.ACCOMMODATION),
    MONTE_CARLO_HOTEL_CASINO("3676", "Monte Carlo Hotel and Casino", "V,M", MerchantCategory.ACCOMMODATION),
    CLIMAT_DE_FRANCE("3677", "Climat De France", "V,M", MerchantCategory.ACCOMMODATION),
    CUMULUS_HOTELS("3678", "Cumulus Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    SILVER_LEGACY_HOTEL_CASINO("3679", "Silver Legacy Hotel and Casino", "V,M", MerchantCategory.ACCOMMODATION),
    HOTEIS_OTHAN("3680", "Hoteis Othan", "V,M", MerchantCategory.ACCOMMODATION),
    ADAMS_MARK("3681", "Adams Mark", "V,M", MerchantCategory.ACCOMMODATION),
    SAHARA_HOTEL_CASINO("3682", "Sahara Hotel and Casino", "V,M", MerchantCategory.ACCOMMODATION),
    BRADBURY_SUITES("3683", "Bradbury Suites", "V,M", MerchantCategory.ACCOMMODATION),
    BUDGET_HOST_INNS("3684", "Budget Host Inns", "V,M", MerchantCategory.ACCOMMODATION),
    BUDGETEL("3685", "Budgetel", "V,M", MerchantCategory.ACCOMMODATION),
    SUISSE_CHALET("3686", "Suisse Chalet", "V,M", MerchantCategory.ACCOMMODATION),
    CLARION_HOTEL("3687", "Clarion Hotel", "V,M", MerchantCategory.ACCOMMODATION),
    COMPRI_HOTEL("3688", "Compri Hotel", "V,M", MerchantCategory.ACCOMMODATION),
    CONSORT("3689", "Consort", "V,M", MerchantCategory.ACCOMMODATION),
    COURTYARD_BY_MARRIOTT("3690", "Courtyard by Marriott", "V,M", MerchantCategory.ACCOMMODATION),
    DILLON_INN("3691", "Dillon Inn", "V,M", MerchantCategory.ACCOMMODATION),
    DOUBLETREE("3692", "Doubletree", "V,M", MerchantCategory.ACCOMMODATION),
    DRURY_INN("3693", "Drury Inn", "V,M", MerchantCategory.ACCOMMODATION),
    ECONOMY_INNS_OF_AMERICA("3694", "Economy Inns Of America", "V,M", MerchantCategory.ACCOMMODATION),
    EMBASSY_SUITES("3695", "Embassy Suites", "V,M", MerchantCategory.ACCOMMODATION),
    EXCEL_INN("3696", "Excel Inn", "V,M", MerchantCategory.ACCOMMODATION),
    FAIRFIELD_HOTEL("3697", "Fairfield Hotel", "V,M", MerchantCategory.ACCOMMODATION),
    HARLEY_HOTEL("3698", "Harley Hotel", "V,M", MerchantCategory.ACCOMMODATION),
    MIDWAY_MOTOR_LODGE("3699", "Midway Motor Lodge", "V,M", MerchantCategory.ACCOMMODATION),
    MOTEL_6("3700", "Motel 6", "V,M", MerchantCategory.ACCOMMODATION),
    LA_MANSION_DEL_RIO("3701", "La Mansion Del Rio", "V,M", MerchantCategory.ACCOMMODATION),
    REGISTRY_HOTELS("3702", "Registry Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    RESIDENCE_INN("3703", "Residence Inn", "V,M", MerchantCategory.ACCOMMODATION),
    ROYCE_HOTEL("3704", "Royce Hotel", "V,M", MerchantCategory.ACCOMMODATION),
    SANDMAN_INN("3705", "Sandman Inn", "V,M", MerchantCategory.ACCOMMODATION),
    SHILO_INN("3706", "Shilo Inn", "V,M", MerchantCategory.ACCOMMODATION),
    SHONEYS_INN("3707", "Shoneys Inn", "V,M", MerchantCategory.ACCOMMODATION),
    VIRGIN_RIVER_HOTEL_CASINO("3708", "Virgin River Hotel and Casino", "V,M", MerchantCategory.ACCOMMODATION),
    SUPER_8_MOTEL("3709", "Super 8 Motel", "V,M", MerchantCategory.ACCOMMODATION),
    RITZ_CARLTON("3710", "Ritz-Carlton", "V,M", MerchantCategory.ACCOMMODATION),
    FLAG_INNS_AUSTRALIA("3711", "Flag Inns (Australia)", "V,M", MerchantCategory.ACCOMMODATION),
    BUFFALO_BILLS_HOTEL_CASINO("3712", "Buffalo Bills Hotel and Casino", "V,M", MerchantCategory.ACCOMMODATION),
    QUALITY_PACIFIC_HOTEL("3713", "Quality Pacific Hotel", "V,M", MerchantCategory.ACCOMMODATION),
    FOUR_SEASONS_AUSTRALIA("3714", "Four Seasons (Australia)", "V,M", MerchantCategory.ACCOMMODATION),
    FAIRFIELD_INN("3715", "Fairfield Inn", "V,M", MerchantCategory.ACCOMMODATION),
    CARLTON_HOTELS("3716", "Carlton Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    CITY_LODGE_HOTELS("3717", "City Lodge Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    KAROS_HOTELS("3718", "Karos Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    PROTEA_HOTELS("3719", "Protea Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    SOUTHERN_SUN_HOTELS("3720", "Southern Sun Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    CONRAD_HOTELS("3721", "Conrad Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    WYNDHAM("3722", "Wyndham", "V,M", MerchantCategory.ACCOMMODATION),
    RICA_HOTELS("3723", "Rica Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    INTER_NOR_HOTELS("3724", "Inter Nor Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    SEA_PINES_RESORT("3725", "Sea Pines Resort", "V,M", MerchantCategory.ACCOMMODATION),
    RIO_SUITES("3726", "Rio Suites", "V,M", MerchantCategory.ACCOMMODATION),
    BROADMOOR_HOTEL("3727", "Broadmoor Hotel", "V,M", MerchantCategory.ACCOMMODATION),
    BALLYS_HOTEL_CASINO("3728", "Ballys Hotel and Casino", "V,M", MerchantCategory.ACCOMMODATION),
    JOHN_ASCUAGAS_NUGGET("3729", "John Ascuagas Nugget", "V,M", MerchantCategory.ACCOMMODATION),
    MGM_GRAND_HOTEL("3730", "MGM Grand Hotel", "V,M", MerchantCategory.ACCOMMODATION),
    HARRAHS_HOTELS_CASINOS("3731", "Harrah’s Hotels and Casinos", "V,M", MerchantCategory.ACCOMMODATION),
    OPRYLAND_HOTEL("3732", "Opryland Hotel", "V,M", MerchantCategory.ACCOMMODATION),
    BOCA_RATON_RESORT("3733", "Boca Raton Resort", "M", MerchantCategory.ACCOMMODATION),
    HARVEY_BRISTOL_HOTELS("3734", "Harvey Bristol Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    MASTERS_ECONOMY_INNS("3735", "Masters Economy Inns", "V,M", MerchantCategory.ACCOMMODATION),
    COLORADO_BELLE_EDGEWATER_RESORT("3736", "Colorado Belle Edgewater Resort", "V,M", MerchantCategory.ACCOMMODATION),
    RIVIERA_HOTEL_CASINO("3737", "Riviera Hotel and Casino", "V,M", MerchantCategory.ACCOMMODATION),
    TROPICANA_RESORT_CASINO("3738", "Tropicana Resort and Casino", "V,M", MerchantCategory.ACCOMMODATION),
    WOODSIDE_HOTELS_RESORTS("3739", "Woodside Hotels and Resorts", "V,M", MerchantCategory.ACCOMMODATION),
    TOWNEPLACE_SUITES("3740", "Towneplace Suites", "V,M", MerchantCategory.ACCOMMODATION),
    MILLENNIUM_BROADWAY_HOTEL("3741", "Millennium Broadway Hotel", "V,M", MerchantCategory.ACCOMMODATION),
    CLUB_MED("3742", "Club Med", "V,M", MerchantCategory.ACCOMMODATION),
    BILTMORE_HOTEL_AND_SUITES("3743", "Biltmore Hotel and Suites", "V,M", MerchantCategory.ACCOMMODATION),
    CAREFREE_RESORTS("3744", "Carefree Resorts", "V,M", MerchantCategory.ACCOMMODATION),
    ST_REGIS_HOTEL("3745", "St. Regis Hotel", "V,M", MerchantCategory.ACCOMMODATION),
    THE_ELIOT_HOTEL("3746", "The Eliot Hotel", "V,M", MerchantCategory.ACCOMMODATION),
    CLUB_CORPORATION_RESORTS("3747", "Club Corporation/Club Resorts", "V,M", MerchantCategory.ACCOMMODATION),
    WELLESLEY_INNS("3748", "Wellesley Inns", "V,M", MerchantCategory.ACCOMMODATION),
    BEVERLY_HILLS_HOTEL("3749", "Beverly Hills Hotel", "V,M", MerchantCategory.ACCOMMODATION),
    CROWNE_PLAZA_HOTELS("3750", "Crowne Plaza Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    HOMEWOOD_SUITES("3751", "Homewood Suites", "V,M", MerchantCategory.ACCOMMODATION),
    PEABODY_HOTELS("3752", "Peabody Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    GREENBRIAR_RESORTS("3753", "Greenbriar Resorts", "V,M", MerchantCategory.ACCOMMODATION),
    AMELIA_ISLAND_PLANTATION("3754", "Amelia Island Plantation", "V,M", MerchantCategory.ACCOMMODATION),
    HOMESTEAD("3755", "Homestead", "V,M", MerchantCategory.ACCOMMODATION),
    CANYON_RANCH("3757", "Canyon Ranch", "TSYS", MerchantCategory.ACCOMMODATION),
    KAHALA_MANDARIN_ORIENTAL("3758", "Kahala Mandarin Oriental Hotel", "V,M", MerchantCategory.ACCOMMODATION),
    ORCHID_AT_MAUNA_LAI("3759", "Orchid At Mauna Lai", "V,M", MerchantCategory.ACCOMMODATION),
    HALEKULANI_WAIKIKI_PARC("3760", "Halekulani Hotel/Waikiki Parc", "V,M", MerchantCategory.ACCOMMODATION),
    PRIMADONNA_HOTEL_CASINO("3761", "Primadonna Hotel and Casino", "V,M", MerchantCategory.ACCOMMODATION),
    WHISKEY_PETES_HOTEL_CASINO("3762", "Whiskey Pete’s Hotel and Casino", "V,M", MerchantCategory.ACCOMMODATION),
    CHATEAU_ELAN_WINERY_RESORT("3763", "Chateau Elan Winery and Resort", "V,M", MerchantCategory.ACCOMMODATION),
    BEAU_RIVAGE_HOTEL_CASINO("3764", "Beau Rivage Hotel and Casino", "V,M", MerchantCategory.ACCOMMODATION),
    BELLAGIO("3765", "Bellagio", "V,M", MerchantCategory.ACCOMMODATION),
    FREMONT_HOTEL_CASINO("3766", "Fremont Hotel and Casino", "V,M", MerchantCategory.ACCOMMODATION),
    MAIN_STREET_STATION_HOTEL_CASINO("3767", "Main Street Station Hotel and Casino", "V,M", MerchantCategory.ACCOMMODATION),
    SILVER_STAR_HOTEL_CASINO("3768", "Silver Star Hotel and Casino", "V,M", MerchantCategory.ACCOMMODATION),
    STRATOSPHERE_HOTEL_CASINO("3769", "Stratosphere Hotel and Casino", "V,M", MerchantCategory.ACCOMMODATION),
    SPRINGHILL_SUITES("3770", "Springhill Suites", "V,M", MerchantCategory.ACCOMMODATION),
    CAESARS_HOTEL_CASINO("3771", "Caesars Hotel and Casino", "V,M", MerchantCategory.ACCOMMODATION),
    NEMACOLIN_WOODLANDS("3772", "Nemacolin Woodlands", "V,M", MerchantCategory.ACCOMMODATION),
    VENETIAN_RESORT_HOTEL_CASINO("3773", "Venetian Resort Hotel and Casino", "V,M", MerchantCategory.ACCOMMODATION),
    NEW_YORK_NEW_YORK_HOTEL_CASINO("3774", "New York-New York Hotel and Casino", "V,M", MerchantCategory.ACCOMMODATION),
    SANDS_RESORT("3775", "Sands Resort", "V,M", MerchantCategory.ACCOMMODATION),
    NEVELE_GRANDE_RESORT("3776", "Nevele Grande Resort and Country Club", "V,M", MerchantCategory.ACCOMMODATION),
    MANDALAY_BAY_RESORT("3777", "Mandalay Bay Resort", "V,M", MerchantCategory.ACCOMMODATION),
    FOUR_POINTS_HOTELS("3778", "Four Points Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    W_HOTELS("3779", "W Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    DISNEYLAND_RESORTS("3780", "Disneyland Resorts", "V,M", MerchantCategory.ACCOMMODATION),
    PATRICIA_GRAND_RESORT_HOTELS("3781", "Patricia Grand Resort Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    ROSEN_HOTEL_AND_RESORTS("3782", "Rosen Hotel and Resorts", "V,M", MerchantCategory.ACCOMMODATION),
    TOWN_AND_COUNTRY_RESORT("3783", "Town and Country Resort and Convention Center", "V,M", MerchantCategory.ACCOMMODATION),
    FIRST_HOSPITALITY_HOTELS("3784", "First Hospitality Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    OUTRIGGER_HOTELS_AND_RESORTS("3785", "Outrigger Hotels and Resorts", "V,M", MerchantCategory.ACCOMMODATION),
    OHANA_HOTELS_OF_HAWAII("3786", "Ohana Hotels of Hawaii", "V,M", MerchantCategory.ACCOMMODATION),
    CARIBE_ROYAL_RESORT_SUITE_VILLAS("3787", "Caribe Royal Resort Suite and Villas", "V,M", MerchantCategory.ACCOMMODATION),
    ALA_MOANA_HOTEL("3788", "Ala Moana Hotel", "V,M", MerchantCategory.ACCOMMODATION),
    SMUGGLERS_NOTCH_RESORT("3789", "Smugglers Notch Resort", "V,M", MerchantCategory.ACCOMMODATION),
    RAFFLES_HOTELS("3790", "Raffles Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    STAYBRIDGE_SUITES("3791", "Staybridge Suites", "V,M", MerchantCategory.ACCOMMODATION),
    CLARIDGE_CASINO_HOTEL("3792", "Claridge Casino Hotel", "V,M", MerchantCategory.ACCOMMODATION),
    THE_FLAMINGO_HOTELS("3793", "The Flamingo Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    GRAND_CASINO_HOTELS("3794", "Grand Casino Hotels", "V,M", MerchantCategory.ACCOMMODATION),
    PARIS_LAS_VEGAS_HOTEL("3795", "Paris Las Vegas Hotel", "V,M", MerchantCategory.ACCOMMODATION),
    PEPPERMILL_HOTEL_CASINO("3796", "Peppermill Hotel Casino", "V,M", MerchantCategory.ACCOMMODATION),
    ATLANTIC_CITY_HILTON("3797", "Atlantic City Hilton", "V,M", MerchantCategory.ACCOMMODATION),
    EMBASSY_VACATION_RESORT("3798", "Embassy Vacation Resort", "V,M", MerchantCategory.ACCOMMODATION),
    HALE_KOA_HOTEL("3799", "Hale Koa Hotel", "V,M", MerchantCategory.ACCOMMODATION),
    HOMESTEAD_SUITES("3800", "Homestead Suites", "V,M", MerchantCategory.ACCOMMODATION),
    WILDERNESS_HOTEL_AND_RESORT("3801", "Wilderness Hotel and Resort", "V,M", MerchantCategory.ACCOMMODATION),
    THE_PALACE_HOTEL("3802", "The Palace Hotel", "V,M", MerchantCategory.ACCOMMODATION),
    THE_WIGWAM_GOLF_RESORT_AND_SPA("3803", "The Wigwam Golf Resort and Spa", "M", MerchantCategory.ACCOMMODATION),
    THE_DIPLOMAT_COUNTRY_CLUB_AND_SPA("3804", "The Diplomat Country Club and Spa", "M", MerchantCategory.ACCOMMODATION),
    THE_ATLANTIC("3805", "The Atlantic", "M", MerchantCategory.ACCOMMODATION),
    PRINCEVILLE_RESORT("3806", "Princeville Resort", "M", MerchantCategory.ACCOMMODATION),
    ELEMENT("3807", "Element", "V,M", MerchantCategory.ACCOMMODATION),
    LXR_LUXURY_RESORTS("3808", "LXR (Luxury Resorts)", "V,M", MerchantCategory.ACCOMMODATION),
    SETTLE_INN("3809", "Settle Inn", "M", MerchantCategory.ACCOMMODATION),
    LA_COSTA_RESORT("3810", "La Costa Resort", "M", MerchantCategory.ACCOMMODATION),
    PREMIER_TRAVEL_INNS("3811", "Premier Travel Inns", "V,M", MerchantCategory.ACCOMMODATION),
    HYATT_PLACE("3812", "Hyatt Place", "V,M", MerchantCategory.ACCOMMODATION),
    HOTEL_INDIGO("3813", "Hotel Indigo", "V,M", MerchantCategory.ACCOMMODATION),
    THE_ROOSEVELT_HOTEL_NY("3814", "The Roosevelt Hotel NY", "V,M", MerchantCategory.ACCOMMODATION),
    NICKELODEON_FAMILY_SUITES("3815", "Nickelodeon Family Suites by Holiday Inn", "V,M", MerchantCategory.ACCOMMODATION),
    HOME2SUITES("3816", "Home2Suites", "V,M", MerchantCategory.ACCOMMODATION),
    AFFINIA("3817", "Affinia", "M", MerchantCategory.ACCOMMODATION),
    MAINSTAY_SUITES("3818", "Mainstay Suites", "V,M", MerchantCategory.ACCOMMODATION),
    OXFORD_SUITES("3819", "Oxford Suites", "V,M", MerchantCategory.ACCOMMODATION),
    JUMEIRAH_ESSEX_HOUSE("3820", "Jumeirah Essex House", "V,M", MerchantCategory.ACCOMMODATION),
    CARIBE_ROYAL("3821", "Caribe Royal", "V,M", MerchantCategory.ACCOMMODATION),
    CROSSLAND("3822", "Crossland", "V,M", MerchantCategory.ACCOMMODATION),
    GRAND_SIERRA_RESORT("3823", "Grand Sierra Resort", "V,M", MerchantCategory.ACCOMMODATION),
    ARIA("3824", "Aria", "V,M", MerchantCategory.ACCOMMODATION),
    VDARA("3825", "Vdara", "V,M", MerchantCategory.ACCOMMODATION),
    AUTOGRAPH("3826", "Autograph", "V,M", MerchantCategory.ACCOMMODATION),
    GALT_HOUSE("3827", "Galt House", "V,M", MerchantCategory.ACCOMMODATION),
    COSMOPOLITAN_LAS_VEGAS("3828", "Cosmopolitan of Las Vegas", "V,M", MerchantCategory.ACCOMMODATION),
    COUNTRY_INN_CARLSON("3829", "Country Inn By Carlson", "V,M", MerchantCategory.ACCOMMODATION),
    PARK_PLAZA_HOTEL("3830", "Park Plaza Hotel", "V,M", MerchantCategory.ACCOMMODATION),
    WALDORF("3831", "Waldorf", "V,M", MerchantCategory.ACCOMMODATION),

    AFFILIATED_AUTO_RENTAL("3351", "Affiliated Auto Rental", "V,M", MerchantCategory.CAR_RENTAL),
    AMERICAN_INTERNATIONAL("3352", "American International", "V,M", MerchantCategory.CAR_RENTAL),
    BROOKS_RENT_A_CAR("3353", "Brooks Rent-A-Car", "V,M", MerchantCategory.CAR_RENTAL),
    ACTION_AUTO_RENTAL("3354", "Action Auto Rental", "V,M", MerchantCategory.CAR_RENTAL),
    SIXT_CAR_RENTAL("3355", "Sixt Car Rental", "V,M", MerchantCategory.CAR_RENTAL),
    HERTZ("3357", "Hertz", "V,M", MerchantCategory.CAR_RENTAL),
    PAYLESS_CAR_RENTAL("3359", "Payless Car Rental", "V,M", MerchantCategory.CAR_RENTAL),
    SNAPPY_CAR_RENTAL("3360", "Snappy Car Rental", "V,M", MerchantCategory.CAR_RENTAL),
    AIRWAYS("3361", "Airways", "V,M", MerchantCategory.CAR_RENTAL),
    ALTRA_AUTO_RENTAL("3362", "Altra Auto Rental", "V,M", MerchantCategory.CAR_RENTAL),
    AGENCY_RENT_A_CAR("3364", "Agency Rent-A-Car", "V,M", MerchantCategory.CAR_RENTAL),
    BUDGET_RENT_A_CAR("3366", "Budget Rent-A-Car", "V,M", MerchantCategory.CAR_RENTAL),
    HOLIDAY_RENT_A_CAR("3368", "Holiday Rent-A-Car", "V,M", MerchantCategory.CAR_RENTAL),
    RENT_A_WRECK("3370", "Rent-A-Wreck", "V,M", MerchantCategory.CAR_RENTAL),
    ACCENT_RENT_A_CAR("3374", "Accent Rent-A-Car", "V,M", MerchantCategory.CAR_RENTAL),
    AJAX_RENT_A_CAR("3376", "Ajax Rent-A-Car", "V,M", MerchantCategory.CAR_RENTAL),
    TRIANGLE_RENT_A_CAR("3380", "Triangle Rent-A-Car", "V,M", MerchantCategory.CAR_RENTAL),
    EUROPCAR("3381", "Europcar", "V,M", MerchantCategory.CAR_RENTAL),
    TROPICAL_RENT_A_CAR("3385", "Tropical Rent-A-Car", "V,M", MerchantCategory.CAR_RENTAL),
    SHOWCASE_RENTAL_CARS("3386", "Showcase Rental Cars", "V,M", MerchantCategory.CAR_RENTAL),
    ALAMO_RENT_A_CAR("3387", "Alamo Rent-A-Car", "V,M", MerchantCategory.CAR_RENTAL),
    MERCHANTS_RENT_A_CAR("3388", "Merchants Rent-A-Car", "V,M", MerchantCategory.CAR_RENTAL),
    AVIS_RENT_A_CAR("3389", "Avis Rent-A-Car", "V,M", MerchantCategory.CAR_RENTAL),
    DOLLAR_RENT_A_CAR("3390", "Dollar Rent-A-Car", "V,M", MerchantCategory.CAR_RENTAL),
    EUROPE_BY_CAR("3391", "Europe By Car", "V,M", MerchantCategory.CAR_RENTAL),
    NATIONAL_CAR_RENTAL("3393", "National Car Rental", "V,M", MerchantCategory.CAR_RENTAL),
    KEMWELL_GROUP("3394", "Kemwell Group", "V,M", MerchantCategory.CAR_RENTAL),
    THRIFTY_CAR_RENTAL("3395", "Thrifty Car Rental", "V,M", MerchantCategory.CAR_RENTAL),
    TILDEN_RENT_A_CAR("3396", "Tilden Rent-A-Car", "V,M", MerchantCategory.CAR_RENTAL),
    ECONO_CAR_RENT_A_CAR("3398", "Econo-Car Rent-A-Car", "V,M", MerchantCategory.CAR_RENTAL),
    AUTO_HOST_RENTAL_CARS("3400", "Auto Host Rental Cars", "V,M", MerchantCategory.CAR_RENTAL),
    ENTERPRISE_RENT_A_CAR("3405", "Enterprise Rent-A-Car", "V,M", MerchantCategory.CAR_RENTAL),
    GENERAL_RENT_A_CAR("3409", "General Rent-A-Car", "V,M", MerchantCategory.CAR_RENTAL),
    A1_RENT_A_CAR("3412", "A1 Rent-A-Car", "V,M", MerchantCategory.CAR_RENTAL),
    GODFREY_NATIONAL("3414", "Godfrey National", "V", MerchantCategory.CAR_RENTAL),
    ANSA_INTERNATIONAL("3420", "Ansa International", "V,M", MerchantCategory.CAR_RENTAL),
    ALLSTATE("3421", "Allstate", "V,M", MerchantCategory.CAR_RENTAL),
    AVCAR("3423", "AVCAR", "V,M", MerchantCategory.CAR_RENTAL),
    AUTOMATE("3425", "Automate", "V,M", MerchantCategory.CAR_RENTAL),
    AVON_RENT_A_CAR("3427", "Avon Rent-A-Car", "V,M", MerchantCategory.CAR_RENTAL),
    CAREY("3428", "Carey", "V,M", MerchantCategory.CAR_RENTAL),
    INSURANCE_RENT_A_CAR("3429", "Insurance Rent-A-Car", "V,M", MerchantCategory.CAR_RENTAL),
    MAJOR_RENT_A_CAR("3430", "Major Rent-A-Car", "V,M", MerchantCategory.CAR_RENTAL),
    REPLACEMENT_RENT_A_CAR("3431", "Replacement Rent-A-Car", "V,M", MerchantCategory.CAR_RENTAL),
    RESERVE_RENT_A_CAR("3432", "Reserve Rent-A-Car", "V,M", MerchantCategory.CAR_RENTAL),
    UGLY_DUCKLING_RENT_A_CAR("3433", "Ugly Duckling Rent-A-Car", "V,M", MerchantCategory.CAR_RENTAL),
    USA("3434", "USA", "V,M", MerchantCategory.CAR_RENTAL),
    VALUE_RENT_A_CAR("3435", "Value Rent-A-Car", "V,M", MerchantCategory.CAR_RENTAL),
    AUTOHANSA("3436", "Autohansa", "V,M", MerchantCategory.CAR_RENTAL),
    CITE("3437", "Cite", "V", MerchantCategory.CAR_RENTAL),
    INTERNET("3438", "Interent", "V,M", MerchantCategory.CAR_RENTAL),
    MILLEVILLE("3439", "Milleville", "V,M", MerchantCategory.CAR_RENTAL),
    ADVANTAGE_RENT_A_CAR("3441", "Advantage Rent A Car", "V,M", MerchantCategory.CAR_RENTAL),


    UNITED_AIRLINES("3000", "United Airlines", "V,M", MerchantCategory.AIRLINES),
    AMERICAN_AIRLINES("3001", "American Airlines", "V,M", MerchantCategory.AIRLINES),
    PAN_AMERICAN("3002", "Pan American", "V,M", MerchantCategory.AIRLINES),
    EUROFLY("3003", "Eurofly", "V,M", MerchantCategory.AIRLINES),
    DRAGON_AIRLINES("3004", "Dragon Airlines", "V,M", MerchantCategory.AIRLINES),
    BRITISH_AIRWAYS("3005", "British Airways", "V,M", MerchantCategory.AIRLINES),
    JAPAN_AIR_LINES("3006", "Japan Air Lines", "V,M", MerchantCategory.AIRLINES),
    AIR_FRANCE("3007", "Air France", "V,M", MerchantCategory.AIRLINES),
    LUFTHANSA_GERMAN_AIRLINES("3008", "Lufthansa German Airlines", "V,M", MerchantCategory.AIRLINES),
    AIR_CANADA("3009", "Air Canada", "V,M", MerchantCategory.AIRLINES),
    KLM_AIRLINES("3010", "Royal Dutch Airlines (KLM Airlines)", "V,M", MerchantCategory.AIRLINES),
    AEROFLOT("3011", "Aeroflot", "V,M", MerchantCategory.AIRLINES),
    QANTAS("3012", "Qantas", "V,M", MerchantCategory.AIRLINES),
    ALITALIA("3013", "Alitalia", "V,M", MerchantCategory.AIRLINES),
    SAUDI_ARABIAN_AIRLINES("3014", "Saudi Arabian Airlines", "V,M", MerchantCategory.AIRLINES),
    SWISS_INTL_AIR_LINES("3015", "Swiss International Air Lines", "V,M", MerchantCategory.AIRLINES),
    SCANDINAVIAN_AIRLINE_SYSTEM("3016", "Scandinavian Airline System (SAS)", "V,M", MerchantCategory.AIRLINES),
    SOUTH_AFRICAN_AIRWAYS("3017", "South African Airways", "V,M", MerchantCategory.AIRLINES),
    VARIG("3018", "Varig", "V,M", MerchantCategory.AIRLINES),
    GERMANWINGS("3019", "Germanwings", "TSYS", MerchantCategory.AIRLINES),
    AIR_INDIA("3020", "Air India", "V,M", MerchantCategory.AIRLINES),
    AIR_ALGERIE("3021", "Air Algerie", "V,M", MerchantCategory.AIRLINES),
    PHILIPPINE_AIRLINES("3022", "Philippine Airlines", "V,M", MerchantCategory.AIRLINES),
    MEXICANA("3023", "Mexicana", "V,M", MerchantCategory.AIRLINES),
    PAKISTAN_INTERNATIONAL("3024", "Pakistan International", "V,M", MerchantCategory.AIRLINES),
    AIR_NEW_ZEALAND("3025", "Air New Zealand Ltd. International", "V,M", MerchantCategory.AIRLINES),
    EMIRATES_AIRLINES("3026", "Emirates Airlines", "V,M", MerchantCategory.AIRLINES),
    UTA_AIRLINE("3027", "Union De Transports Aeriens (UTA/interair)", "V,M", MerchantCategory.AIRLINES),
    AIR_MALTA("3028", "Air Malta", "V,M", MerchantCategory.AIRLINES),
    SN_BRUSSELS_AIRLINES("3029", "SN Brussels Airlines", "V,M", MerchantCategory.AIRLINES),
    AEROLINEAS_ARGENTINAS("3030", "Aerolineas Argentinas", "V,M", MerchantCategory.AIRLINES),
    OLYMPIC_AIRWAYS("3031", "Olympic Airways", "V,M", MerchantCategory.AIRLINES),
    EL_AL("3032", "El Al", "V,M", MerchantCategory.AIRLINES),
    ANSETT_AIRLINES("3033", "Ansett Airlines", "V,M", MerchantCategory.AIRLINES),
    ETIHADAIR("3034", "Etihadair", "V,M", MerchantCategory.AIRLINES),
    TAP_AIR_PORTUGAL("3035", "TAP Air Portugal (TAP)", "V,M", MerchantCategory.AIRLINES),
    VASP("3036", "Viacao Aerea Sao Pãulo (VASP)", "V,M", MerchantCategory.AIRLINES),
    EGYPTAIR("3037", "Egyptair", "V,M", MerchantCategory.AIRLINES),
    KUWAIT_AIRWAYS("3038", "Kuwait Airways", "V,M", MerchantCategory.AIRLINES),
    AVIANCA("3039", "Avianca", "V,M", MerchantCategory.AIRLINES),
    GULF_AIR("3040", "Gulf Air (Bahrain)", "V,M", MerchantCategory.AIRLINES),
    BALKAN_BULGARIAN_AIRLINES("3041", "Balkan-Bulgarian Airlines", "V,M", MerchantCategory.AIRLINES),
    FINNAIR("3042", "Finnair", "V,M", MerchantCategory.AIRLINES),
    AER_LINGUS("3043", "Aer Lingus", "V,M", MerchantCategory.AIRLINES),
    AIR_LANKA("3044", "Air Lanka", "V,M", MerchantCategory.AIRLINES),
    NIGERIA_AIRWAYS("3045", "Nigeria Airways", "V,M", MerchantCategory.AIRLINES),
    CRUZEIRO_DO_SUL("3046", "Cruzeiro Do Sul", "V,M", MerchantCategory.AIRLINES),
    TURK_HAVA_YOLLARI("3047", "Turk Hava Yollari", "V,M", MerchantCategory.AIRLINES),
    ROYAL_AIR_MAROC("3048", "Royal Air Maroc", "V,M", MerchantCategory.AIRLINES),
    TUNIS_AIR("3049", "Tunis Air", "V,M", MerchantCategory.AIRLINES),
    ICELANDAIR("3050", "Icelandair", "V,M", MerchantCategory.AIRLINES),
    AUSTRIAN_AIRLINES("3051", "Austrian Airlines", "V,M", MerchantCategory.AIRLINES),
    LAN_AIRLINES("3052", "LAN Airlines", "V,M", MerchantCategory.AIRLINES),
    AVIACO("3053", "Aviacion Y Comercio (AVIACO)", "V,M", MerchantCategory.AIRLINES),
    LADECO("3054", "Linea Aerea Del Cobre (LADECO)", "V,M", MerchantCategory.AIRLINES),
    LAB_AERO_BOLIVIANO("3055", "Lloyd Aero Boliviano (LAB)", "V,M", MerchantCategory.AIRLINES),
    JET_AIRWAYS("3056", "Jet Airways", "V,M", MerchantCategory.AIRLINES),
    VIRGIN_AMERICA("3057", "Virgin America", "V,M", MerchantCategory.AIRLINES),
    DELTA("3058", "Delta", "V,M", MerchantCategory.AIRLINES),
    DBA_AIRLINE("3059", "DBA Airline", "V,M", MerchantCategory.AIRLINES),
    NORTHWEST_AIRLINES("3060", "Northwest Airlines", "V,M", MerchantCategory.AIRLINES),
    CONTINENTAL("3061", "Continental", "V,M", MerchantCategory.AIRLINES),
    HLX_AIR("3062", "Hapag-Lloyd Express", "V,M", MerchantCategory.AIRLINES),
    US_AIRWAYS("3063", "US Airways", "V,M", MerchantCategory.AIRLINES),
    ADRIA_AIRWAYS("3064", "Adria Airways", "V,M", MerchantCategory.AIRLINES),
    AIRINTER("3065", "Airinter", "V,M", MerchantCategory.AIRLINES),
    SOUTHWEST_AIRLINES("3066", "Southwest Airlines", "V,M", MerchantCategory.AIRLINES),
    VANGUARD_AIRLINES("3067", "Vanguard Airlines", "V,M", MerchantCategory.AIRLINES),
    AIR_ASTANA("3068", "Air Astana", "V,M", MerchantCategory.AIRLINES),
    SUN_COUNTRY_AIRLINES("3069", "Sun Country Airlines", "V,M", MerchantCategory.AIRLINES),
    AIR_BRITISH_COLUMBIA("3071", "Air British Columbia", "V,M", MerchantCategory.AIRLINES),
    CEBU_PACIFIC_AIRLINES("3072", "Cebu Pacific Airlines", "V,M", MerchantCategory.AIRLINES),
    SINGAPORE_AIRLINES("3075", "Singapore Airlines", "V,M", MerchantCategory.AIRLINES),
    AEROMEXICO("3076", "Aeromexico", "V,M", MerchantCategory.AIRLINES),
    THAI_AIRWAYS("3077", "Thai Airways", "V,M", MerchantCategory.AIRLINES),
    CHINA_AIRLINES("3078", "China Airlines", "V,M", MerchantCategory.AIRLINES),
    JETSTAR_AIRWAYS("3079", "Jetstar Airways", "V,M", MerchantCategory.AIRLINES),
    KOREAN_AIRLINES("3082", "Korean Airlines", "V,M", MerchantCategory.AIRLINES),
    AIR_AFRIQUE("3083", "Air Afrique", "V,M", MerchantCategory.AIRLINES),
    EVA_AIRWAYS("3084", "Eva Airways", "V,M", MerchantCategory.AIRLINES),
    MIDWEST_EXPRESS_AIRLINES("3085", "Midwest Express Airlines", "V,M", MerchantCategory.AIRLINES),
    CARNIVAL_AIRLINES("3086", "Carnival Airlines", "V,M", MerchantCategory.AIRLINES),
    METRO_AIRLINES("3087", "Metro Airlines", "V,M", MerchantCategory.AIRLINES),
    CROATIA_AIR("3088", "Croatia Air", "V,M", MerchantCategory.AIRLINES),
    TRANSAERO("3089", "Transaero", "V,M", MerchantCategory.AIRLINES),
    UNI_AIRWAYS_CORP("3090", "Uni Airways Corporation", "V,M", MerchantCategory.AIRLINES),
    ZAMBIA_AIRWAYS("3094", "Zambia Airways", "V,M", MerchantCategory.AIRLINES),
    AIR_ZIMBABWE("3096", "Air Zimbabwe Corp", "V,M", MerchantCategory.AIRLINES),
    SPANAIR("3097", "Spanair", "V,M", MerchantCategory.AIRLINES),
    ASIANA_AIRLINES("3098", "Asiana Airlines", "V,M", MerchantCategory.AIRLINES),
    CATHAY_PACIFIC("3099", "Cathay Pacific", "V,M", MerchantCategory.AIRLINES),
    MALAYSIAN_AIRLINE_SYSTEM("3100", "Malaysian Airline System", "V,M", MerchantCategory.AIRLINES),
    IBERIA("3102", "Iberia", "V,M", MerchantCategory.AIRLINES),
    GARUDA("3103", "Garuda", "V,M", MerchantCategory.AIRLINES),
    BRAATHENS("3106", "Braathens S.A.F.E.", "V,M", MerchantCategory.AIRLINES),
    WINGS_AIRWAYS("3110", "Wings Airways", "V,M", MerchantCategory.AIRLINES),
    BRITISH_MIDLAND("3111", "British Midland", "V,M", MerchantCategory.AIRLINES),
    WINDWARD_ISLAND("3112", "Windward Island", "V,M", MerchantCategory.AIRLINES),
    TOWER_AIR("3115", "Tower Air", "V,M", MerchantCategory.AIRLINES),
    VENEZOLANA_INTERNATIONAL("3117", "Venezolana International De Aviacion", "V,M", MerchantCategory.AIRLINES),
    VALLEY_AIRLINES("3118", "Valley Airlines", "V,M", MerchantCategory.AIRLINES),

    I_PURCHASING_PILOT("9034", "I-Purchasing Pilot", "TSYS", MerchantCategory.GOVERNMENT_SERVICES),
    COURT_COSTS_ALIMONY_CHILD_SUPPORT("9211", "Court Costs Including Alimony and Child Support", "V,M", MerchantCategory.GOVERNMENT_SERVICES),
    FINES("9222", "Fines", "V,M", MerchantCategory.GOVERNMENT_SERVICES),
    BAIL_BOND_PAYMENTS("9223", "Bail and Bond Payments", "V,M", MerchantCategory.GOVERNMENT_SERVICES),
    TAX_PAYMENTS("9311", "Tax Payments", "V,M", MerchantCategory.GOVERNMENT_SERVICES),
    GOV_SERVICES_NEC("9399", "Government Services–Not Elsewhere Classified", "V,M", MerchantCategory.GOVERNMENT_SERVICES),
    I_PURCHASING_PILOT_9401("9401", "I-Purchasing Pilot", "TSYS", MerchantCategory.GOVERNMENT_SERVICES),
    POSTAL_SERVICES_GOV("9402", "Postal Services–Government Only", "V,M", MerchantCategory.GOVERNMENT_SERVICES),
    INTRA_GOV_PURCHASES("9405", "Intra-Government Purchases–Government Only", "V,M", MerchantCategory.GOVERNMENT_SERVICES),
    AUTOMATED_REFERRAL_SERVICE("9700", "Automated Referral Service", "V", MerchantCategory.GOVERNMENT_SERVICES),
    VISA_CREDENTIAL_SERVER("9701", "Visa Credential Server", "V", MerchantCategory.GOVERNMENT_SERVICES),
    GCAS_EMERGENCY_SERVICES("9702", "GCAS Emergency Services", "V", MerchantCategory.GOVERNMENT_SERVICES),
    UK_SUPERMARKETS_ELECTRONIC("9751", "UK Supermarkets, Electronic Hot File", "TSYS", MerchantCategory.GOVERNMENT_SERVICES),
    UK_PETROL_STATIONS_ELECTRONIC("9752", "UK Petrol Stations, Electronic Hot File", "TSYS", MerchantCategory.GOVERNMENT_SERVICES),
    GAMBLING_STATE_LOTTERY("9754", "Gambling-Horse, Dog Racing, State Lottery", "M", MerchantCategory.GOVERNMENT_SERVICES),
    INTRA_COMPANY_PURCHASES("9950", "Intra-Company Purchases", "V,M", MerchantCategory.GOVERNMENT_SERVICES),

    DOCTORS_NEC("8011", "Doctors–not elsewhere classified", "V,M", MerchantCategory.PROFESSIONAL_SERVICES),
    DENTISTS_ORTHODONTISTS("8021", "Dentists and Orthodontists", "V,M", MerchantCategory.PROFESSIONAL_SERVICES),
    OSTEOPATHIC_PHYSICIANS("8031", "Osteopathic Physicians", "V,M", MerchantCategory.PROFESSIONAL_SERVICES),
    CHIROPRACTORS("8041", "Chiropractors", "V,M", MerchantCategory.PROFESSIONAL_SERVICES),
    OPTOMETRISTS_OPHTHALMOLOGISTS("8042", "Optometrists and Ophthalmologists", "V,M", MerchantCategory.PROFESSIONAL_SERVICES),
    OPTICIANS("8043", "Opticians, Optical Goods and Eyeglasses", "V,M", MerchantCategory.PROFESSIONAL_SERVICES),
    OPTICAL_GOODS_EYEGLASSES("8044", "Optical Goods and Eyeglasses", "TSYS", MerchantCategory.PROFESSIONAL_SERVICES),
    CHIROPODISTS_PODIATRISTS("8049", "Chiropodists, Podiatrists", "V,M", MerchantCategory.PROFESSIONAL_SERVICES),
    NURSING_PERSONAL_CARE("8050", "Nursing and Personal Care Facilities", "V,M", MerchantCategory.PROFESSIONAL_SERVICES),
    HOSPITALS("8062", "Hospitals", "V,M", MerchantCategory.PROFESSIONAL_SERVICES),
    DENTAL_MEDICAL_LABS("8071", "Dental and Medical Laboratories", "V,M", MerchantCategory.PROFESSIONAL_SERVICES),
    HEALTH_PRACTITIONERS_NEC("8099", "Health Practitioners, Medical Services–Not Elsewhere Classified", "V,M", MerchantCategory.PROFESSIONAL_SERVICES),
    ATTORNEYS("8111", "Attorneys, Legal Services", "V,M", MerchantCategory.PROFESSIONAL_SERVICES),
    SCHOOLS_ELEMENTARY_SECONDARY("8211", "Schools, Elementary and Secondary", "V,M", MerchantCategory.PROFESSIONAL_SERVICES),
    COLLEGES_UNIVERSITIES("8220", "Colleges, Universities, Professional Schools and Junior Colleges", "V,M", MerchantCategory.PROFESSIONAL_SERVICES),
    SCHOOLS_CORRESPONDENCE("8241", "Schools, Correspondence", "V,M", MerchantCategory.PROFESSIONAL_SERVICES),
    SCHOOLS_BUSINESS_SECRETARIAL("8244", "Schools, Business and Secretarial", "V,M", MerchantCategory.PROFESSIONAL_SERVICES),
    SCHOOLS_TRADE_VOCATIONAL("8249", "Schools, Trade and Vocational", "V,M", MerchantCategory.PROFESSIONAL_SERVICES),
    SCHOOLS_EDUCATIONAL_NEC("8299", "Schools And Educational Services–Not Elsewhere Classified", "V,M", MerchantCategory.PROFESSIONAL_SERVICES),
    CHILD_CARE_SERVICES("8351", "Child Care Services", "V,M", MerchantCategory.PROFESSIONAL_SERVICES),
    CHARITABLE_SOCIAL_ORGS("8398", "Organizations, Charitable and Social Service", "V,M", MerchantCategory.PROFESSIONAL_SERVICES),
    ASSOCIATIONS_CIVIC_SOCIAL_FRATERNAL("8641", "Associations–Civic, Social and Fraternal", "V,M", MerchantCategory.PROFESSIONAL_SERVICES),
    ORGANIZATIONS_POLITICAL("8651", "Organizations, Political", "V,M", MerchantCategory.PROFESSIONAL_SERVICES),
    ORGANIZATIONS_RELIGIOUS("8661", "Organizations, Religious", "V,M", MerchantCategory.PROFESSIONAL_SERVICES),
    AUTOMOBILE_ASSOCIATIONS("8675", "Automobile Associations", "V,M", MerchantCategory.PROFESSIONAL_SERVICES),
    MEMBERSHIP_ORGS_NEC("8699", "Organizations, Membership–Not Elsewhere Classified", "V,M", MerchantCategory.PROFESSIONAL_SERVICES),
    TESTING_LABS_NON_MEDICAL("8734", "Testing Laboratories (Non-Medical)", "V,M", MerchantCategory.PROFESSIONAL_SERVICES),
    TESTING_LABS_NON_MEDICAL_TSYS("8743", "Testing Laboratories (Non-Medical)", "TSYS", MerchantCategory.PROFESSIONAL_SERVICES),
    ARCH_ENG_SURVEY_SERVICES("8911", "Architectural, Engineering and Surveying Services", "V,M", MerchantCategory.PROFESSIONAL_SERVICES),
    ACCOUNTING_AUDITING_BOOKKEEPING("8931", "Accounting, Auditing and Bookkeeping Services", "V,M", MerchantCategory.PROFESSIONAL_SERVICES),
    PROFESSIONAL_SERVICES_NEC("8999", "Professional Services–Not Elsewhere Classified", "V,M", MerchantCategory.PROFESSIONAL_SERVICES),

    ADVERTISING_SERVICES("7311", "Advertising Services", "V,M", MerchantCategory.BUSINESS_SERVICES),
    CONSUMER_CREDIT_REPORTING("7321", "Consumer Credit Reporting Agencies", "V,M", MerchantCategory.BUSINESS_SERVICES),
    BLUEPRINTING_PHOTOCOPY("7332", "Blueprinting and Photocopying Services", "TSYS", MerchantCategory.BUSINESS_SERVICES),
    COMMERCIAL_ART_GRAPHICS("7333", "Commercial Art, Graphics, Photography", "V,M", MerchantCategory.BUSINESS_SERVICES),
    QUICK_COPY_REPRODUCTION("7338", "Quick Copy, Reproduction and Blueprinting Services", "V,M", MerchantCategory.BUSINESS_SERVICES),
    STENOGRAPHIC_SECRETARIAL("7339", "Stenographic and Secretarial Support Services", "V,M", MerchantCategory.BUSINESS_SERVICES),
    EXTERMINATING_DISINFECTING("7342", "Exterminating and Disinfecting Services", "V,M", MerchantCategory.BUSINESS_SERVICES),
    CLEANING_JANITORIAL("7349", "Cleaning and Maintenance, Janitorial Services", "V,M", MerchantCategory.BUSINESS_SERVICES),
    EMPLOYMENT_AGENCIES("7361", "Employment Agencies and Temporary Help Services", "V,M", MerchantCategory.BUSINESS_SERVICES),
    COMPUTER_PROGRAMMING_DATA("7372", "Computer Programming, Data Processing and Integrated System Design Services", "V,M", MerchantCategory.BUSINESS_SERVICES),
    INFORMATION_RETRIEVAL("7375", "Information Retrieval Services", "V,M", MerchantCategory.BUSINESS_SERVICES),
    COMPUTER_MAINTENANCE_NEC("7379", "Computer Maintenance, Repair And Services–Not Elsewhere Classified", "V,M", MerchantCategory.BUSINESS_SERVICES),
    CONSULTING_MANAGEMENT_PR("7392", "Consulting, Management and Public Relations Services", "V,M", MerchantCategory.BUSINESS_SERVICES),
    SECURITY_DETECTIVE_AGENCIES("7393", "Detective Agencies, Protective Agencies, Security Services including Armored Cars, Guard Dogs", "V,M", MerchantCategory.BUSINESS_SERVICES),
    EQUIPMENT_RENTAL_LEASING("7394", "Equipment Rental and Leasing Services, Furniture Rental, Tool Rental", "V,M", MerchantCategory.BUSINESS_SERVICES),
    PHOTO_DEVELOPING("7395", "Photo Developing, Photofinishing Laboratories", "V,M", MerchantCategory.BUSINESS_SERVICES),
    BUSINESS_SERVICES_NEC("7399", "Business Services Not Elsewhere Classified", "V,M", MerchantCategory.BUSINESS_SERVICES),

    AUTO_RENTAL_AGENCY_NEC("7512", "Automobile Rental Agency–Not Elsewhere Classified", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),
    TRUCK_RENTAL("7513", "Truck Rental", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),
    MOTOR_HOME_RV_RENTAL("7519", "Motor Home and Recreational Vehicle Rental", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),
    AUTOMOBILE_PARKING("7523", "Automobile Parking Lots and Garages", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),
    EXPRESS_PAYMENT_PARKING("7524", "Express Payment Service Merchants–Parking Lots and Garages", "TSYS", MerchantCategory.RECREATION_ENTERTAINMENT),

    AUTO_BODY_REPAIR("7531", "Automotive Body Repair Shops", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),
    TIRE_RETREAD_REPAIR("7534", "Tire Retreading and Repair Shops", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),
    AUTOMOTIVE_PAINT_SHOPS("7535", "Automotive Paint Shops", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),
    AUTOMOTIVE_SERVICE_SHOPS("7538", "Automotive Service Shops", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),
    CAR_WASHES("7542", "Car Washes", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),
    TOWING_SERVICES("7549", "Towing Services", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),

    ELECTRONIC_REPAIR("7622", "Electronic Repair Shops", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),
    AC_REPAIR("7623", "Air Conditioning and Refrigeration Repair Shops", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),
    APPLIANCE_REPAIR("7629", "Appliance Repair Shops, Electrical and Small", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),
    CLOCK_JEWELRY_WATCH_REPAIR("7631", "Clock, Jewelry and Watch Repair Shops", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),
    FURNITURE_REPAIR_REFINISHING("7641", "Furniture–Reupholstery, Repair and Refinishing", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),
    WELDING_REPAIR("7692", "Welding Repair", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),
    MISC_REPAIR_SHOPS("7699", "Miscellaneous Repair Shops and Related Services", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),

    GOVERNMENT_LOTTERY("7800", "Government Owned Lottery", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),
    GOVERNMENT_LICENSED_CASINOS("7801", "Government-Licensed Casinos (Online or Internet Gambling)", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),
    GOVERNMENT_LICENSED_RACING("7802", "Government-Licensed Horse/Dog Racing", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),

    MOTION_PICTURE_VIDEO_PRODUCTION("7829", "Motion Picture and Video Tape Production and Distribution", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),
    MOTION_PICTURE_THEATERS("7832", "Motion Picture Theaters", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),
    EXPRESS_PAYMENT_MOVIE_THEATER("7833", "Express Payment Service — Motion Picture Theater", "TSYS", MerchantCategory.RECREATION_ENTERTAINMENT),
    DVD_VIDEO_RENTAL("7841", "DVD/Video Tape Rental Stores", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),

    DANCE_HALLS_SCHOOLS("7911", "Dance Halls, Schools and Studios", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),
    THEATRICAL_PRODUCERS("7922", "Theatrical Producers (Except Motion Pictures), Ticket Agencies", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),
    BANDS_ORCHESTRAS("7929", "Bands, Orchestras and Miscellaneous Entertainers–Not Elsewhere Classified", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),
    POOL_BILLIARD_ESTABLISHMENTS("7932", "Pool and Billiard Establishments", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),
    BOWLING_ALLEYS("7933", "Bowling Alleys", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),
    ATHLETIC_FIELDS_SPORTS("7941", "Athletic Fields, Commercial Sports, Professional Sports Clubs, Sports Promoters", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),

    TOURIST_ATTRACTIONS("7991", "Tourist Attractions and Exhibits", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),
    GOLF_COURSES_PUBLIC("7992", "Golf Courses, Public", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),
    VIDEO_AMUSEMENT_GAME_SUPPLIES("7993", "Video Amusement Game Supplies", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),
    VIDEO_GAME_ARCADES("7994", "Video Game Arcades and Establishments", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),
    GAMBLING_TRANSACTIONS("7995", "Gambling Transactions", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),
    AMUSEMENT_PARKS_CARNIVALS("7996", "Amusement Parks, Carnivals, Circuses, Carnivals, Fortune Tellers", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),
    CLUBS_COUNTRY_CLUBS("7997", "Clubs–Country Clubs, Membership (Athletic, Recreation, Sports), Private Golf Courses", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),
    AQUARIUMS_ZOOS("7998", "Aquariums, Dolphinariums, Zoos and Seaquariums", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),
    RECREATION_SERVICES_NEC("7999", "Recreation Services–Not Elsewhere Classified", "V,M", MerchantCategory.RECREATION_ENTERTAINMENT),

    RENT("6513", "Rent", "V,M", MerchantCategory.RENT),

    EQUIPMENT_FURNITURE_HOME_FURNISHINGS("5712", "Equipment, Furniture and Home Furnishings Stores", "V,M", MerchantCategory.MISCELLANEOUS_STORES),
    FLOOR_COVERING_STORES("5713", "Floor Covering Stores", "V,M", MerchantCategory.MISCELLANEOUS_STORES),
    DRAPERY_UPHOLSTERY_WINDOW_COVERINGS("5714", "Drapery, Upholstery and Window Coverings Stores", "V,M", MerchantCategory.MISCELLANEOUS_STORES),
    FIREPLACE_STORES("5718", "Fireplace, Fireplace Screens and Accessories Stores", "V,M", MerchantCategory.MISCELLANEOUS_STORES),
    MISC_HOUSE_FURNISHING_SHOPS("5719", "Miscellaneous House Furnishing Specialty Shops", "V,M", MerchantCategory.MISCELLANEOUS_STORES),
    HOUSEHOLD_APPLIANCE_STORES("5722", "Household Appliance Stores", "V,M", MerchantCategory.MISCELLANEOUS_STORES),
    ELECTRONICS_SALES("5732", "Electronics Sales", "V,M", MerchantCategory.MISCELLANEOUS_STORES),
    MUSIC_STORES("5733", "Music Stores–Musical Instruments, Pianos and Sheet Music", "V,M", MerchantCategory.MISCELLANEOUS_STORES),
    COMPUTER_SOFTWARE_STORES("5734", "Computer Software Stores", "V,M", MerchantCategory.MISCELLANEOUS_STORES),
    RECORD_SHOPS("5735", "Record Shops", "V,M", MerchantCategory.MISCELLANEOUS_STORES),

    CATERERS("5811", "Caterers", "V,M", MerchantCategory.FOOD_SERVICES),
    EATING_PLACES_RESTAURANTS("5812", "Eating Places and Restaurants", "V,M", MerchantCategory.FOOD_SERVICES),
    BARS_NIGHTCLUBS("5813", "Bars, Cocktail Lounges, Discotheques, Nightclubs and Taverns–Drinking Places", "V,M", MerchantCategory.ALCOHOL),
    FAST_FOOD_RESTAURANTS("5814", "Fast Food Restaurants", "V,M", MerchantCategory.FOOD_SERVICES),
    DIGITAL_GOODS_BOOKS_MOVIES_MUSIC("5815", "Digital Goods: Books, Movies, Music", "V,M", MerchantCategory.DIGITAL_GOODS),
    DIGITAL_GOODS_GAMES("5816", "Digital Goods: Games", "V,M", MerchantCategory.DIGITAL_GOODS),
    DIGITAL_GOODS_APPLICATIONS("5817", "Digital Goods: Applications (Excludes Games)", "V,M", MerchantCategory.DIGITAL_GOODS),
    DIGITAL_GOODS_LARGE_MULTI_CATEGORY("5818", "Digital Goods: Large Digital Goods / Multi-Category", "V,M", MerchantCategory.DIGITAL_GOODS),

    DRUG_STORES_PHARMACIES("5912", "Drug Stores and Pharmacies", "V,M", MerchantCategory.RETAIL),
    PACKAGE_STORES_BEER_WINE_LIQUOR("5921", "Package Stores–Beer, Wine and Liquor", "V,M", MerchantCategory.RETAIL),
    SECOND_HAND_STORES("5931", "Second Hand Stores, Used Merchandise Stores", "V,M", MerchantCategory.RETAIL),
    ANTIQUE_SHOPS("5932", "Antique Shops–Sales, Repairs and Restoration Services", "V,M", MerchantCategory.RETAIL),
    PAWN_SHOPS("5933", "Pawn Shops", "V,M", MerchantCategory.RETAIL),
    WRECKING_SALVAGE_YARDS("5935", "Wrecking and Salvage Yards", "V,M", MerchantCategory.RETAIL),
    ANTIQUE_REPRODUCTION_STORES("5937", "Antique Reproduction Stores", "V,M", MerchantCategory.RETAIL),
    BICYCLE_SHOPS("5940", "Bicycle Shops–Sales and Service", "V,M", MerchantCategory.RETAIL),
    SPORTING_GOODS_STORES("5941", "Sporting Goods Stores", "V,M", MerchantCategory.RETAIL),
    BOOK_STORES("5942", "Book Stores", "V,M", MerchantCategory.RETAIL),

    // Clothing Stores
    MENS_BOYS_CLOTHING_ACCESSORIES("5611", "Men’s and Boys’ Clothing and Accessories Stores", "V,M", MerchantCategory.CLOTHING),
    WOMENS_READY_TO_WEAR("5621", "Women’s Ready to Wear Stores", "V,M", MerchantCategory.CLOTHING),
    WOMENS_ACCESSORY_SPECIALTY("5631", "Women’s Accessory and Specialty Stores", "V,M", MerchantCategory.CLOTHING),
    CHILDRENS_INFANTS_WEAR("5641", "Children’s and Infants’ Wear Stores", "V,M", MerchantCategory.CLOTHING),
    FAMILY_CLOTHING_STORES("5651", "Family Clothing Stores", "V,M", MerchantCategory.CLOTHING),
    SPORTS_RIDING_APPAREL("5655", "Sports Apparel, and Riding Apparel Stores", "V,M", MerchantCategory.CLOTHING),
    SHOE_STORES("5661", "Shoe Stores", "V,M", MerchantCategory.CLOTHING),
    FURRIERS_FUR_SHOPS("5681", "Furriers and Fur Shops", "V,M", MerchantCategory.CLOTHING),
    MENS_WOMENS_CLOTHING("5691", "Men’s and Women’s Clothing Stores", "V,M", MerchantCategory.CLOTHING),
    ALTERATIONS_MENDING_TAILORS("5697", "Alterations, Mending, Seamstresses, Tailors", "V,M", MerchantCategory.CLOTHING),
    WIG_TOUPEE_SHOPS("5698", "Wig and Toupee Shops", "V,M", MerchantCategory.CLOTHING),
    ACCESSORY_APPAREL_MISC("5699", "Accessory and Apparel Stores–Miscellaneous", "V,M", MerchantCategory.CLOTHING),

    // Retail Outlet Services (MCC 5000–5599)
    MOTOR_VEHICLE_SUPPLIES_NEW_PARTS("5013", "Motor Vehicle Supplies and New Parts", "V,M", MerchantCategory.AUTOMOTIVE),
    OFFICE_COMMERCIAL_FURNITURE("5021", "Office and Commercial Furniture", "V,M", MerchantCategory.OFFICE_SUPPLIES),
    CONSTRUCTION_MATERIALS_NEC("5039", "Construction Materials Not Elsewhere Classified", "V,M", MerchantCategory.BUILDING_SUPPLIES),
    OFFICE_PHOTOGRAPHIC_MICROFILM_EQUIPMENT("5044", "Office, Photographic, Photocopy and Microfilm Equipment", "V,M", MerchantCategory.OFFICE_SUPPLIES),
    COMPUTERS_COMPUTER_PERIPHERAL_SOFTWARE("5045", "Computers, Computer Peripheral Equipment, Software", "V,M", MerchantCategory.OFFICE_SUPPLIES),
    COMMERCIAL_EQUIPMENT_NEC("5046", "Commercial Equipment Not Elsewhere Classified", "V,M", MerchantCategory.OFFICE_SUPPLIES),
    DENTAL_LAB_MEDICAL_OPHTHALMIC_HOSPITAL_EQUIPMENT("5047", "Dental/Laboratory/Medical/Ophthalmic Hospital Equipment and Supplies", "V,M", MerchantCategory.MEDICAL_EQUIPMENT),
    METAL_SERVICE_CENTERS_OFFICES("5051", "Metal Service Centers and Offices", "V,M", MerchantCategory.BUILDING_SUPPLIES),
    ELECTRICAL_PARTS_EQUIPMENT("5065", "Electrical Parts and Equipment", "V,M", MerchantCategory.BUILDING_SUPPLIES),
    HARDWARE_EQUIPMENT_SUPPLIES("5072", "Hardware Equipment and Supplies", "V,M", MerchantCategory.BUILDING_SUPPLIES),
    PLUMBING_HEATING_EQUIPMENT("5074", "Plumbing and Heating Equipment", "V,M", MerchantCategory.BUILDING_SUPPLIES),
    INDUSTRIAL_SUPPLIES_NEC("5085", "Industrial Supplies Not Elsewhere Classified", "V,M", MerchantCategory.INDUSTRIAL),
    PRECIOUS_STONES_METALS_WATCHES_JEWELRY("5094", "Precious Stones and Metals, Watches and Jewelry", "V,M", MerchantCategory.DURABLE_GOODS),
    DURABLE_GOODS_NEC("5099", "Durable Goods Not Elsewhere Classified", "V,M", MerchantCategory.DURABLE_GOODS),
    STATIONERY_OFFICE_SUPPLIES_PRINTING_WRITING_PAPER("5111", "Stationery, Office Supplies, Printing and Writing Paper", "V,M", MerchantCategory.OFFICE_SUPPLIES),
    DRUGS_DRUG_PROPRIETORS_DRUGGISTS_SUNDRIES("5122", "Drugs, Drug Proprietors and Druggists Sundries", "V,M", MerchantCategory.NON_DURABLE_GOODS),
    PIECE_GOODS_NOTIONS_DRY_GOODS("5131", "Piece Goods, Notions, and Other Dry Goods", "V,M", MerchantCategory.NON_DURABLE_GOODS),
    UNIFORMS_COMMERCIAL_CLOTHING("5137", "Men’s, Women’s and Children’s Uniforms and Commercial Clothing", "V,M", MerchantCategory.CLOTHING),
    COMMERCIAL_FOOTWEAR("5139", "Commercial Footwear", "V,M", MerchantCategory.CLOTHING),
    CHEMICALS_ALLIED_PRODUCTS_NEC("5169", "Chemicals and Allied Products Not Elsewhere Classified", "V,M", MerchantCategory.INDUSTRIAL),
    PETROLEUM_PRODUCTS("5172", "Petroleum and Petroleum Products", "V,M", MerchantCategory.FUEL),
    BOOKS_PERIODICALS_NEWSPAPERS("5192", "Books, Periodicals and Newspapers", "V,M", MerchantCategory.NON_DURABLE_GOODS),
    FLORIST_SUPPLIES_NURSERY_STOCK_FLOWERS("5193", "Florists Supplies, Nursery Stock and Flowers", "V,M", MerchantCategory.NON_DURABLE_GOODS),
    PAINTS_VARNISHES_SUPPLIES("5198", "Paints, Varnishes and Supplies", "V,M", MerchantCategory.BUILDING_SUPPLIES),
    NON_DURABLE_GOODS_NEC("5199", "Non-Durable Goods Not Elsewhere Classified", "V,M", MerchantCategory.NON_DURABLE_GOODS),
    HOME_SUPPLY_WAREHOUSE_STORES("5200", "Home Supply Warehouse Stores", "V,M", MerchantCategory.BUILDING_SUPPLIES),
    BUILDING_MATERIALS_LUMBER_STORES("5211", "Building Materials, Lumber Stores", "V,M", MerchantCategory.BUILDING_SUPPLIES),
    GLASS_PAINT_WALLPAPER_STORES("5231", "Glass, Paint, Wallpaper Stores", "V,M", MerchantCategory.BUILDING_SUPPLIES),
    HARDWARE_STORES("5251", "Hardware Stores", "V,M", MerchantCategory.BUILDING_SUPPLIES),
    LAWN_GARDEN_SUPPLY_STORES("5261", "Lawn and Garden Supply Stores", "V,M", MerchantCategory.BUILDING_SUPPLIES),
    MOBILE_HOME_DEALERS("5271", "Mobile Home Dealers", "V,M", MerchantCategory.AUTOMOTIVE),
    WAREHOUSE_CLUB_GAS("5299", "Warehouse Club Gas", "TSYS", MerchantCategory.FUEL),
    WHOLESALE_CLUBS("5300", "Wholesale Clubs", "V,M", MerchantCategory.RETAIL),
    DUTY_FREE_STORES("5309", "Duty Free Stores", "V,M", MerchantCategory.RETAIL),
    DISCOUNT_STORES("5310", "Discount Stores", "V,M", MerchantCategory.RETAIL),
    DEPARTMENT_STORES("5311", "Department Stores", "V,M", MerchantCategory.RETAIL),
    VARIETY_STORES("5331", "Variety Stores", "V,M", MerchantCategory.RETAIL),
    MISC_GENERAL_MERCHANDISE_STORES("5399", "Miscellaneous General Merchandise Stores", "V,M", MerchantCategory.RETAIL),
    GROCERY_SUPERMARKETS("5411", "Grocery Stores, Supermarkets", "V,M", MerchantCategory.FOOD),
    FREEZER_LOCKER_MEAT_PROVISIONERS("5422", "Freezer and Locker Meat Provisioners", "V,M", MerchantCategory.FOOD),
    CANDY_NUT_CONFECTIONERY_STORES("5441", "Candy, Nut and Confectionery Stores", "V,M", MerchantCategory.FOOD),
    DAIRY_PRODUCTS_STORES("5451", "Dairy Products Stores", "V,M", MerchantCategory.FOOD),
    BAKERIES("5462", "Bakeries", "V,M", MerchantCategory.FOOD),
    MISC_FOOD_CONVENIENCE_MARKETS_SPECIALTY_VENDING("5499", "Miscellaneous Food Stores–Convenience Stores, Markets, Specialty Stores, and Vending Machines", "V,M", MerchantCategory.FOOD),
    AUTOMOBILE_TRUCK_DEALERS("5511", "Automobile and Truck Dealers–Sales, Service, Repairs, Parts and Leasing", "V,M", MerchantCategory.AUTOMOTIVE),
    USED_AUTOMOBILE_TRUCK_DEALERS("5521", "Automobile and Truck Dealers–(Used Only)–Sales", "V,M", MerchantCategory.AUTOMOTIVE),
    AUTOMOTIVE_TIRE_STORES("5532", "Automotive Tire Stores", "V,M", MerchantCategory.AUTOMOTIVE),
    AUTOMOTIVE_PARTS_ACCESSORIES_STORES("5533", "Automotive Parts and Accessories Stores", "V,M", MerchantCategory.AUTOMOTIVE),
    SERVICE_STATIONS("5541", "Service Stations (With or Without Ancillary Services)", "V,M", MerchantCategory.FUEL),
    FUEL_DISPENSER_AUTOMATED("5542", "Fuel Dispenser, Automated", "V,M", MerchantCategory.FUEL),
    BOAT_DEALERS("5551", "Boat Dealers", "V,M", MerchantCategory.AUTOMOTIVE),
    CAMPER_DEALERS_RECREATIONAL_UTILITY_TRAILERS("5561", "Camper Dealers, Recreational and Utility Trailers", "V,M", MerchantCategory.AUTOMOTIVE),
    MOTORCYCLE_SHOPS_DEALERS("5571", "Motorcycle Shops and Dealers", "V,M", MerchantCategory.AUTOMOTIVE),
    MOTOR_HOME_DEALERS("5592", "Motor Home Dealers", "V,M", MerchantCategory.AUTOMOTIVE),
    SNOWMOBILE_DEALERS("5598", "Snowmobile Dealers", "V,M", MerchantCategory.AUTOMOTIVE),
    MISC_AUTOMOTIVE_AIRCRAFT_FARM_EQUIPMENT_DEALERS("5599", "Miscellaneous Automotive, Aircraft, and Farm Equipment Dealers–Not Elsewhere Classified", "V,M", MerchantCategory.AUTOMOTIVE),

    // Telecommunication & Utilities (MCC 4800–4999)
    TELECOMMUNICATION_EQUIPMENT("4812", "Telecommunication Equipment Including Telephone Sales", "V,M", MerchantCategory.TELECOMMUNICATIONS),
    KEY_ENTRY_TELECOM("4813", "Key-Entry Telecom Merchant providing single local and long-distance phone calls using a central access number in a non-face-to-face environment using key entry", "M", MerchantCategory.TELECOMMUNICATIONS),
    TELECOMMUNICATION_SERVICES("4814", "Telecommunication Services including but not limited to prepaid phone services and recurring phone services", "V,M", MerchantCategory.TELECOMMUNICATIONS),
    COMPUTER_NETWORK_INFORMATION_SERVICES("4816", "Computer Network/Information Services", "V,M", MerchantCategory.TELECOMMUNICATIONS),
    TELEGRAPH_SERVICES("4821", "Telegraph Services", "V,M", MerchantCategory.TELECOMMUNICATIONS),
    WIRE_TRANSFER_MONEY_ORDERS("4829", "Wire Transfer Money Orders (V, D, G, X) Money Transfer (M)", "V,M", MerchantCategory.FINANCIAL_SERVICES),
    CABLE_SATELLITE_PAY_TV_RADIO("4899", "Cable, Satellite, and Other Pay Television and Radio Services", "V,M", MerchantCategory.TELECOMMUNICATIONS),
    UTILITIES_ELECTRIC_GAS_HEATING_WATER("4900", "Utilities–Electric, Gas, Heating Oil, Sanitary, Water", "V,M", MerchantCategory.UTILITIES),

    // Transportation Services (MCC 4000–4799)
    RAILROADS_FREIGHT("4011", "Railroads–Freight", "V,M", MerchantCategory.TRANSPORTATION),
    SUBURBAN_LOCAL_COMMUTER("4111", "Transportation–Suburban and Local Commuter Passenger, including Ferries", "V,M", MerchantCategory.TRANSPORTATION),
    PASSENGER_RAILWAYS("4112", "Passenger Railways", "V,M", MerchantCategory.TRANSPORTATION),
    AMBULANCE_SERVICES("4119", "Ambulance Services", "V,M", MerchantCategory.TRANSPORTATION),
    TAXICABS_LIMOUSINES("4121", "Taxicabs and Limousines", "V,M", MerchantCategory.TRANSPORTATION),
    BUS_LINES("4131", "Bus Lines", "V,M", MerchantCategory.TRANSPORTATION),
    MOTOR_FREIGHT_CARRIERS("4214", "Motor Freight Carriers, Trucking–Local/Long Distance, Moving and Storage Companies, Local Delivery", "V,M", MerchantCategory.TRANSPORTATION),
    COURIER_SERVICES("4215", "Courier Services–Air and Ground, Freight Forwarders", "V,M", MerchantCategory.TRANSPORTATION),
    PUBLIC_WAREHOUSING("4225", "Public Warehousing–Farm Products, Refrigerated Goods, Household Goods Storage", "V,M", MerchantCategory.TRANSPORTATION),
    CRUISE_LINES("4411", "Cruise Lines", "V,M", MerchantCategory.TRANSPORTATION),
    BOAT_LEASES_RENTALS("4457", "Boat Leases and Boat Rentals", "V,M", MerchantCategory.TRANSPORTATION),
    MARINAS_MARINE_SERVICES_SUPPLIES("4468", "Marinas, Marine Service/Supplies", "V,M", MerchantCategory.TRANSPORTATION),
    AIR_CARRIERS_AIRLINES_NEC("4511", "Air Carriers, Airlines–not elsewhere classified", "V,M", MerchantCategory.TRANSPORTATION),
    AIRPORTS_TERMINALS_FLYING_FIELDS("4582", "Airports, Airport Terminals, Flying Fields", "V,M", MerchantCategory.TRANSPORTATION),
    TRAVEL_AGENCIES_TOUR_OPERATORS("4722", "Travel Agencies and Tour Operators", "V,M", MerchantCategory.TRANSPORTATION),
    PACKAGE_TOUR_OPERATORS_GERMANY_ONLY("4723", "Package Tour Operators (Germany Only)", "V", MerchantCategory.TRANSPORTATION),
    TELEMARKETING_TRAVEL_VITAMINS("4761", "Telemarketing of Travel Related Services and Vitamins", "TSYS", MerchantCategory.TRANSPORTATION),
    BRIDGE_ROAD_FEES_TOLLS("4784", "Bridge and Road Fees, Tolls", "V,M", MerchantCategory.TRANSPORTATION),
    TRANSPORTATION_SERVICES_NEC("4789", "Transportation Services Not Elsewhere Classified", "V,M", MerchantCategory.TRANSPORTATION),

    // Contractors, Specialty Services, Publishing & Cleaning (MCC 1500–2999)
    GENERAL_CONTRACTORS_RESIDENTIAL_COMMERCIAL("1520", "General Contractors–Residential and Commercial", "V,M", MerchantCategory.CONTRACTORS),
    AIR_CONDITIONING_HEATING_PLUMBING_CONTRACTORS("1711", "Air Conditioning, Heating and Plumbing Contractors", "V,M", MerchantCategory.CONTRACTORS),
    ELECTRICAL_CONTRACTORS("1731", "Electrical Contractors", "V,M", MerchantCategory.CONTRACTORS),
    INSULATION_MASONRY_PLASTER_STONE_TILE_CONTRACTORS("1740", "Insulation, Masonry, Plastering, Stonework and Tile Setting Contractors", "V,M", MerchantCategory.CONTRACTORS),
    CARPENTRY_CONTRACTORS("1750", "Carpentry Contractors", "V,M", MerchantCategory.CONTRACTORS),
    ROOFING_SIDING_SHEET_METAL_CONTRACTORS("1761", "Roofing and Siding, Sheet Metal Work Contractors", "V,M", MerchantCategory.CONTRACTORS),
    CONCRETE_WORK_CONTRACTORS("1771", "Concrete Work Contractors", "V,M", MerchantCategory.CONTRACTORS),
    SPECIAL_TRADE_CONTRACTORS_NEC("1799", "Contractors, Special Trade Contractors–not elsewhere classified", "V,M", MerchantCategory.CONTRACTORS),
    MISC_PUBLISHING_PRINTING("2741", "Miscellaneous Publishing and Printing", "V,M", MerchantCategory.PUBLISHING_PRINTING),
    TYPESETTING_PLATE_MAKING_RELATED_SERVICES("2791", "Typesetting, Plate Making and Related Services", "V,M", MerchantCategory.PUBLISHING_PRINTING),
    SANITATION_POLISHING_SPECIALTY_CLEANING_PREPARATIONS("2842", "Sanitation, Polishing and Specialty Cleaning Preparations", "V,M", MerchantCategory.SPECIALTY_SERVICES),

    // Agricultural Services (MCC 0001–1499)
    VETERINARY_SERVICES("0742", "Veterinary Services", "V,M", MerchantCategory.AGRICULTURAL_SERVICES),
    AGRICULTURAL_COOPERATIVES("0763", "Agricultural Cooperatives", "V,M", MerchantCategory.AGRICULTURAL_SERVICES),
    HORTICULTURAL_LANDSCAPING_SERVICES("0780", "Horticultural and Landscaping Services", "V,M", MerchantCategory.AGRICULTURAL_SERVICES);

    private final String mcc;
    private final String description;
    private final String supportedBrands;
    private final MerchantCategory merchantCategory;

    public static MerchantCategoryCodes getMerchantCategoryCode(String mcc) {
        return Arrays.stream(MerchantCategoryCodes.values())
                .filter(merchantCategoryCode -> merchantCategoryCode.getMcc().equals(mcc))
                .findFirst()
                .orElse(null);
    }
}
